### ISSUE TITLE
Migrate videos to Youtube 

### ISSUE THREAD

**Issue by yochannah** [open-life-science/ols-governance#8]
Camille - could I get you to migrate the old videos here: [https://studio.youtube.com/channel/UCs12-ZgnDJOWIWN3Vo1XHXA/videos/upload?c=UCs12-ZgnD[…]ype%22%3A%22date%22%2C%22sortOrder%22%3A%22DESCENDING%22%7D](https://studio.youtube.com/channel/UCs12-ZgnDJOWIWN3Vo1XHXA/videos/upload?c=UCs12-ZgnDJOWIWN3Vo1XHXA&filter=%5B%7B%22name%22%3A%22VISIBILITY%22%2C%22value%22%3A%5B%22UNLISTED%22%5D%7D%5D&sort=%7B%22columnType%22%3A%22date%22%2C%22sortOrder%22%3A%22DESCENDING%22%7D) to the new youtube channel by the end of the month, please? Please use the title YYYY-MM, e.g. 2023-06 and keep them unlisted.

**Comment by Camille-Gonzalez-VA** [comment]
Just found this in my archived notifications but this was completed a while back I believe. This was before our reset re: task management. @yochannah could you confirm if this was done they way you were looking for so we can close or I can complete?

**Comment by yochannah** [comment]
could you please double-check that the titles are all in YYYY-MM Format?

**Comment by Camille-Gonzalez-VA** [comment]
Update/add-on from sync w Yo: Check if all cohort call are on Youtube.

**Comment by yochannah** [comment]
correction - all governance calls, on the gov channel (not cohort)

**Comment by Camille-Gonzalez-VA** [comment]
Q1: Does the Pre-OLS-Gov-Mingles Mtg need to be posted on Youtube as well?
Q2: OLS-Gov-Mingles Oct 30, 2023 is only 1 minute long, does that need to be posted as well?
Q3: OLS-Gov-Mingles Jun 24, 2024 is 7 min long, does that need to be posted as well?

Everything else has been uploaded and deleted from Zoom. @yochannah

**Comment by Camille-Gonzalez-VA** [comment]
Questions above were answered during sync. Task is complete.
